project:
  type: website

website:
  title: "Comentari-de-Text"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ./pages/about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    toc-title: Índex
    toc-location: left
    number-sections: true
    code-overflow: wrap
    highlight-style: arrow



