project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "Comentari de Text"

  favicon: img/ic.png
  navbar:
    logo: img/ic.png
    left:
      - href: pages/Frases.qmd
        text: Frases Fetes i Locucions
      - href: pages/connectors.qmd
        text: Connectors
      - pages/Plantillas.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    toc-title: Índex
    toc-location: left
    number-sections: true
    code-overflow: wrap
    highlight-style: arrow
