---
title: "Comentari de Text"
---

# Abans de començar
- Numerar les línies de 5 en 5
- Llegir el text amb atenció
- Observar les característiques externes del text
    - Títol
    - Subratllats
    - ...
- Subratllar mots i frases claus
- Determinar parts temàtiques

# Tema i Parts temàtiques

Abans d'introduir el tema cal fer una breu introducció sobre el text que anem a comentar. Per a fer-la utilitzem informació de la cita final: autor, llibre, data de publicació...

## Tema

Sintagma nominal de 10 paraules com a màxim que respon a la pregunta: de què tracta el text? Dins no pot tindre verbs conjugats, però si formes personals (infinitiu, gerundi i participi).

<div class="pl">
Aquest text escrit per <input> al <input> presenta com a tema <input>.
</div>

## Parts Temàtiques

- Cada part a d'anar en un paràgraf escrit
- Fem resum de cada part, amb idees principals ~~Enumeració idees~~
    - Idea completa (Subjecte + Verb + Complements)

En l'assaig i l'article d'opinió n'hi ha tres parts: **Introducció, Desenvolupament y Conclusió**. A més el text literari no te pars determinades

<div class="pl">
Podem dividir el text en les següents parts bàsiques:

La primera part que correspon al primer paràgraf i la idea principal és <input> (l x-y).

La segona part que abasta <input> i la idea principal és <input> (l x-y).

La tercera part que abraça l’últim paràgraf i la idea principal és <input> (l x-y).
</div>

### Conectors per a introduir les línies
- Compren
- Abraça
- Abasta
- Correspon

# Estructura Externa

## Títol

Determinar la relació entre el títol i el tema del text

- **Títol temàtic:** el títol correspon amb el tema del text, a més a d'incluir l'opinió del autor acerca del tema.
- **Títol parcialment temátic:** té relació amb el tema però no completa
- **Títol remátic:** no té cap relació amb el tema ni expressa l'opinió de l'autor. L'unic que tracta es de cridar l'atenció del lector per a que llija

## Cos
Cal esmentar el número de línies del text i de paragràfs que té el text

## Cita final
S'ha d'interpretar tota la infomació que hi aparega: autor, nom llibre,
nom periòdic, lloc de publicació, editorial, data de publicació, pàgines d’on s’ha extret...

## Plantilla

<div class="pl">

Aquest text escrit per <input> al diari <input> i publicat el dia  <input> consta de <input> línies distribuïdes en <input> paràgrafs. A més, presenta un títol:<select>
<option>[Tria]</option>
<option>
TEMÀTIC car guarda una relació directa amb el tema del text.</option>
<option>REMÀTIC car no guarda relació amb el tema del text.</option>
<option> PARCIALMENT TEMÀTIC car guarda relació amb el tema del text però no és una </option>relació completa. </select>
</div>

# Tipologia

Estudiarem 5 tipologies:

<div class="accordion" id="accordionExample">
<div class="accordion-item">
<p class="accordion-header" id="headingTwo">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
Expositiva
</button>
</p>
<div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
<div class="accordion-body">

**Finalitat:** infromar d'algun aspecte de manera objectiva

<hr>

**Justificació** (3 exemples del text mínim):

- Respondre breument a la pregunta: *què esposa?* Resumir breument què es allò que proposa el text
- L'us de verbs i pronoms en 3a persona
- L'us de lèxic **no** valoratiu
- Oracions enunciatives
- Verbs en indicatiu

</div>
</div>
</div>
<div class="accordion-item">
<p class="accordion-header" id="headingThree">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
Argumentativa</button>
</p>
<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
<div class="accordion-body">


**Finalitat:** opinar o convéncer

<hr>

**Justificació** (3 exemples del text mínim):

- Respondre breument a la pregunta: *què argumenta?* Resumir breument què es allò que proposa el text
- L'us de verbs i pronoms en 1a persona
- L'us de lèxic valoratiu
- Oracions exclamatives, interrogatives, exhortatives, desideratives i dubitatives
- Verbs en subjuntiu
- Presencia de tesi i arguments


</div>
</div>
</div>
<div class="accordion-item">
<p class="accordion-header" id="headingFive">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
Descriptiva</button>
</p>
<div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
<div class="accordion-body">


**Finalitat:** descriure persones, objectes, llocs, sensacions, sentiments

<hr>

**Justificació** (3 exemples del text mínim):

- Respondre breument a la pregunta: *què descriu?* Resumir breument què es allò que proposa el text
- Abundància d'adjectius propis de la descripció en detriment de verbs d'acció
- L'us de de recursos literaris com la metàfora, o la comparació
<br/>
- Si el text esta en passat:
    - L'ús de l'imperfet que és el verb que s'usa per descriure el pasat


</div>
</div>
</div>
<div class="accordion-item">
<p class="accordion-header" id="headingOne">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
Narrativa</button>
</p>
<div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
<div class="accordion-body">


**Finalitat:** narrar fets, esdeveniments de manera ordenada

<hr>

**Justificació** (3 exemples del text mínim):

- Respondre breument a la pregunta: *què descriu?* Resumir breument què es allò que proposa el text
- Abundància d'adjectius propis de la descripció en detriment de verbs d'acció
- L'us de de recursos literaris com la metàfora, o la comparació
<br/>
- Si el text esta en passat:
    - L'ús del passat simple o passat perifràstic que són els verbs que s'usen per narrament passat

</div>
</div>
</div>
<div class="accordion-item">
<p class="accordion-header" id="headingFour">
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
Conversacional</button>
</p>
<div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
<div class="accordion-body">


**Finalitat:** Transcriure una conversa oral

<hr>

**Justificació** (3 exemples del text mínim):

- Respondre breument a les  preguntes: *qui parla?*, *de què?* i *en quin estil?*. Resumir en un sol paràgraf
- L'us de recursos tipogràfics com les cometes i els guions
- L'us de preguntes de comprovació de canal, onomatopeies, falques lingüístiques
</div>
</div>
</div>
</div>
<br/>
Per cada tipologia que observe al text:

1. Identificar cada tipologia
2. Localitzar: per línies, per paràgrafs, per parts bàsiques
3. Justificar amb dos trets: assenyalar exactament què és allò que s'està copiant per a justificar cada tipologia
