---
title: Connectors
--- 
# CLASSES DE CONNECTORS:
## Connectors que funcionen com a organitzadors del text:
### Per iniciar l'escrit o començar el text:
- El motiu d'aquest escrit (d'aquesta carta) és... 
- L'objectiu principal d'aquest escrit és...
- Ens adrecem (M'adrece) a vosté per...
- Acabem de rebre la seua carta...
- Amb aquestes línies pretenem...
- Ens proposem d'exposar....
- Aquest escrit tracta de...
- L'exposició següent té l'objectiu....
- La meua intenció en escriure aquest (llibre, article...) és.... 
- La finalitat de posar-nos en
contacte amb vosté és...
- Ens sap greu comunicar-vos... 
- Escric aquestes línies per...
### Per avançar en el text i marcar l'ordre d'exposició:
- En primer lloc, en segon lloc... per últim.
- D'una banda.
- d'altra banda...
- Primerament
- a continuació
- finalment... - D'entrada direm que...
- Seguidament exposarem...
- A continuació em referiré...
- Immediatament després...
- Tot seguit, passe a exposar-vos...
- Un cop dit això, us comentaré que...
- Després d'això que hem dit...
- Pel que fa això últim...
- Com hem estat dient fins ara...
- Quant al que acabe de dir...
- Reprenent el que dèiem fa un moment...
- A part del que hem exposat fins ara...
- I encara podem afegir que....
- En relació amb el que acabem de dir...
- Quant a ...
- Referent a aquesta última qüestió...
### Per concloure el text
- Com a conclusió final...
- De tot això, en podem extreure...
 - Per concloure...( Per acabar...)
- Tal com hem vist...
- En definitiva... (En resum...)
- Com a recapitulació...
- Finalment...
- Les conclusions d'això que acabem de dir... 
- Com a resultat del que hem exposat...
- Doncs bé, per acabar...
- Per tant...
- Així doncs...
## Connectors organitzadors, que relacionen frases i paràgrafs:
### Connectors temporals:
- En el moment de...
- Mentre
- Quan
- Al cap d'una estona
- Al cap de mitja hora
- Després
- Anteriorment
- Poc abans
- Al mateix temps
- Llavors... aleshores
- Simultàniament
- Més tard
- Més endavant
- Tot seguit
- A continuació
- Enacabant...
### Connectors exemplificadors:
- Per exemple
- Per posar un exemple
- Això és
- És a dir
- Per il lustrar tot el que diem
- Com a mostra d'això
- I ara posarem/ un exemple d'això
### Connectors per insistir o continuar sobre el mateix punt:
- A més a més
- A més
- A més d’això 
- I encara més
- Així
mateix
- Tanmateix
- Així doncs
- Tot seguit
- D'altra banda...
### D'oposició i objecció:
- Però
- En canvi
- Malgrat que
- No obstant això
- Amb tot
- Tot i que
- Tot i això
- Ara bé
- Encara que
- Al contrari
- Tanmateix 
- amb tot i amb això...
### Connectors que indiquen temps:
- Abans
- Ara
- Després
- Anteriorment
- Poc abans
- Al mateix temps
- Simultàniament
- En el mateix moment
- Llavors
- Poc després
- Més tard
- Més endavant
- A continuació
- Tot seguit...
### Connectors que indiquen causa:
- Perquè
- Vist que
- A causa de
- A causa que
- Ja que
- Puix que
- Per culpa de
- Com que
- Car
- Atés que
- Considerant que...
### Connectors que indiquen conseqüència:
- Doncs
- Per tant
- Per això
- De manera que
- Per aquest motiu
- Cosa que
- Així és que
- Per consegüent
- En conseqüència...
### Connectors que indiquen condició:
- A condició que
- A condició de.
- En cas que
- En cas de
- Només que
- Amb què
- Si...
### Connectors que indiquen finalitat:
- Per tal que
- Per tal de
- perquè
- A fi de
- A fi que
- Amb l'objectiu que
- Amb l'objectiu de...

# CONSIDERACIONS A TENIR EN COMPTE AMB ELS CONNECTORS:
- Cal ser originals i no repetir sempre els mateixos connectors. Això farà el text més atractiu al lector i evitarà la monotonia.
- Si utilitzem connectors dobles, hem de recordar-nos-en d'incloure sempre les segones parts: 
    - D'una banda... .D'altra banda,... .
    - En primer lloc,... .En segon lloc,... .
- Cal utilitzar sempre els connectors amb propietat (ben utilitzats) i amb mesura (evitant els innecessaris), perquè un abús o un ús innecessari d’aquests dificulta la comprensió del text i l'ompli de tòpics buits de contingut.
- Els connectors han d'ocupar llocs clau dins de l'escrit (sovint van al començament del paràgraf o de la frase i van separats de la resta de la frase amb una coma).