---
title: "Plantillas"
---

# Tema

Aquest text escrit per _______al________presenta com a tema________.

 
# Parts Temàtiques

Podem dividir el text en les següents parts bàsiques:

La primera part que correspon al primer paràgraf i la idea principal és ___________(l x-y).

La segona part que abasta ___________ i la idea principal és ___________(l x-y).

La tercera part que abraça l’últim paràgraf i la idea principal és ___________(l x-y).

<hr/>

Podem dividir el text en les següents parts bàsiques:

La primera part o introducció que correspon al primer paràgraf i la idea principal és (+infinitiu) _____(l x-y).

La segona part o desenvolupament que abasta des de la línia___fins la__i la ideaprincipal és (+ infinitiu) _______(l x-y).

La tercera part o conclusió que abraça l’últim paràgraf i la idea principal és (+infinitiu)_________(l x-y).

# Estructura Externa

Aquest text escrit per ___________ al diari ___________ i publicat el dia  ___________ consta de ___________ línies distribuïdes en ___________ paràgrafs. A més, presenta un títol:<select>
<option>[Tria]</option>
<option>
TEMÀTIC car guarda una relació directa amb el tema del text.</option>
<option>REMÀTIC car no guarda relació amb el tema del text.</option>
<option> PARCIALMENT TEMÀTIC car guarda relació amb el tema del text però no és una </option>relació completa. </select>

<hr/>
Aquest text escrit per_______al llibre______i publicat per l’editorial______l’any_____i que correspon a les pàgines ______ d’aquest llibre, consta de ______ línies distribuïdes en _______paràgrafs. A més, presenta un títol:
<select>
<option>[Tria]</option>
<option>
TEMÀTIC car guarda una relació directa amb el tema del text.</option>
<option>REMÀTIC car no guarda relació amb el tema del text.</option>
<option> PARCIALMENT TEMÀTIC car guarda relació amb el tema del text però no és una </option>relació completa. </select>

# Resum

Podem resumir el text de la següent manera: ( punt i a banda, escrivim a la línia de baix).

<hr/>
Un possible resum del text seria: ( punt i a banda, escrivim a la línia de baix).

# Tipologia

La tipologia ___________ en el ______ car (argumenta, descriu, narra,...)_______. Apareix reforçada amb l'ús de _________.


Malgrat les diferents tipologies presents al text, s'observa un clar domini de la tipologia:_____

# Tesi, Estructura Textual i Arguments

L’estructura textual d’aquest text és ____________ car podem observar la tesi de l’autor/a a ____________ . Aquesta defén la idea que______________________ [explicar amb les teues paraules quina és la tesi de l’autor]. A més, l’autor reforça la seua tesi amb diferents arguments com ara:

# Veus del Discurs
## Assaig

Pel que fa a les veus del discurs, extratextualment, d’una banda, s’observa l’autor real que és________, a més el lector real som nosaltres, que ara mateix estem fent el comentari del text. D’altra banda, l’autor model és una persona preocupada per_____interessada a ______. Alhora que el lector model és aquell qui comparteix les mateixes inquietuds i preocupacions que l’autor model i és capaç d’entendre el text i la seua enciclopèdia.

Intratextualment, identifiquem el locutor que és ________i coincideix amb l’autor real car aquest no és un text de ficció.

De igual mode, l’al·locutari també coincideix amb el lector model.

*( solament en el cas que tinga al·locutari distint al lector model) Malgrat que l’al·locutari no coincideix amb el lector model car és________. 

S’observa també un enunciador, concretament la veu de _________a la línia ____que amb estil_______(directe o indirecte) comenta que __________________.

S’observa també un intratext, concretament la veu de _________a la línia ____que amb estil_______(directe o indirecte) comenta que __________________.

## Text Literari

Pel que fa a les veus del discurs, extratextualment, s’observa l’autor real que és________, a més el lector real som nosaltres, que ara mateix estem fent el comentari del text.
    
Intratextualment, identifiquem el locutor que és un narrador_________ (*identificar i justificar el tipus de narrador). Aquest locutor no coincideix amb l’autor real car és un text de ficció.
    
A més, l’al·locutari és______ ( solament en cas que en tinga sinó no posem res).

S’observa també un enunciador, concretament la veu de _________a la línia ____que amb estil_______(directe o indirecte) comenta que __________________. 

S’observa també un intratext, concretament la veu de _________a la línia ____que amb estil_______(directe o indirecte) comenta que __________________.


# Varietat Dialectal

Podem adscriure el text a la varietat dialectal _________com s’observa per l’ús de característiques com:

