---
title: "Resum"

format:
  html:
    toc: false
    toc-location: body

---

# Text Exemple

Quan a l'abril Washington DC va inaugurar el seu servei de bicing -en la promoció del servei es va destacar l'èxit que havia tingut a ciutats com París i Barcelona- va ser rebut amb un cert escepticisme. Hi va haver gent que va fer apostes sobre quant temps trigarien els aparcaments de les bicicletes a patir atacs vandàlics o quantes bicis es 7robarien al dia, i també es va posar en dubte que amb el clima de la ciutat la idea funcionés. La primavera i la tardor són temperades i ideals per pedalejar. però la humitat i la calor a 1'estiu i el fred i la neu a l'hivern, en principi, ho desaconsellen.

El mateix ajuntament va llançar el bicing amb certa cautela. No és pas que no haja afició a la bicicleta a Washington (a la ciutat hi ha uns circuits extraordinaris entre boscos però, això sí, molt pocs calTils bici urbans), sinó que la idea era (i ho continua sent) inèdita als EUA. D'aquesta manera, el servei va començar amb tan sols 120 bicicletes (10 estacions amb 12 màquines) i una tarifa anual de 40 dòlars (uns 31 euro s) per a lloguers de tres hores. Quan els responsables van veure que s'estima que el preu del sistema per bicicleta a Europa puja 4500 dòlars (uns 3500 euro s, segons s'ha publicat a la premsa local), el primer que van fer va ser buscar un patrocinador privat que cobrís les despeses.

Ho van aconseguir, i poc més de sis mesos després les xifres indiquen que la ciutadania respon: 900 persones inscrites, uns 100 viatges al dia i la idea d'ampliar-lo la primavera que ve. Les principals queixes són per I 'horari (per motius de seguretat l'última bicicleta es pot agafar a les deu de la nit) i sorprèn el civisme: només una bicicleta ha estat robada fins ara. l és que el que al principi podia haver estat el principal problema (el trànsit abundant i a vegades fins i tot salvatge) ha acabat sent el principal avantatge. Fins a tal punt que diverses organitzacions de ciclistes estan promovent a Internet l'Ús del bicing i també a la bicicleta privada com a millor forma de transpOli ara, a l 'hivern, quan la neu ja ha aparegut a la ciutat. Els dies de grans nevades moure's per Washington és una tortura més gran del que ja ho és en condicions normals, així que la bicicleta, diuen els seus defensors, és la millor opció.

# Exemple Resumen Errat

En aquest text l'autor diu que (1) a Washington DC han posat (2) el servei de bicing. La gent va fer apostes sobre quant temps trigarien els aparcaments de les bicicletes a patir atacs vandàlics (3) o quantes bicis es robarien al dia. La neu i el calor desaconsellen l'ús de la bicicleta. (4)L'ajuntament va implantar el servei amb cautela per l'inèdit de la idea als Estats Units. Però a la ciutat hi ha uns circuits extraordinaris (5) entre boscos; per això (6) el servei va començar només amb 120 bicicletes, 1l estacions i 12 màquines, i costava 40 dòlars, que són 31 euros, per a lloguers de tres hores (7) .. Tot seguit el text parla del fet que (l) la iniciativa del bicing va tenir èxit. A la primavera, més bicis. (8) De fet no s'han robat (9) les bicis, i la bici (10) s'ha vist com una iniciativa eficaç al transit salvatge (5) de la ciutat. Alguns han fet (2) en Internet una defensa del transport de la bicicleta quan la neu ja aparegut a la ciutat (3). A l'hivern el transit és una tortura (5). L'autor diu que (1)(11) a l'hivern (10) amb els problemes de trànsit la bicicleta és el millor (2).

<hr />

1. Cal evitar aquesta estructura, que crea un distanciament innecessari respecte del text original.
2. Poca concreció terminològica.
3. Repetició literal del text original, desaconsellada.
4. Oració mal connectada amb el fragment discursiu anterior. També hi ha un error
d'interpretació, perquè aquesta afirmació s'ha de reportar al parer de "la gent" Si no es fa així s'entén erròniament que és l'autor del text qui fa l'afirmació.
5. No convé passar al resum la modalització de l'autor.
6. Manca de coherència. perquè amb l'estructura proposada el connector consecutiu busca la seua causa en els circuits entre els boscos (incoherència) i no en la cautela de l'ajuntament (idea i oració anterior que sí n'és la causa).
7. Idees secundàries irrellevants.
8. Esquematisme. Cal redactar oracions i lligar-les bé al context discursiu.
9. Interpretació correcta però error de dada: sí que n'han robat una.
10. Repetició innecessària.
11. Mala interpretació: no es l'autor el que ho pensa, sinó els defensors de la bicicleta.
<br/><br/>

<button type="button" class="btn btn-dark" role="link"><a href="../index.html">Retornar a Comentari de Text</a></button>